# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20191031_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
